---
all:
  hosts: 
    cvaas: 
      ansible_host: www.arista.io
      ansible_user: cvaas
      ansible_password: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcwODkzNDMxODEzNjM3MDgzNjYsImRzbiI6ImFyaXN0YS10bmctMDUiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxODE4ODMyNzE5LCJpYXQiOjE3MjI1ODMxMjEsIm9naSI6NzA4OTM0MzE4MTM2MzcwMjAzMSwib2duIjoiYXJpc3RhLXRuZy0wNSIsInNpZCI6IjQ0ZDY4ZDM3YzMyOWQ5ZDQ2Mjc5NWVjZDcyNjU5MTI1M2Q2ZGM4ZjdmNjA1ZjM4Nzg5MGI3YWFlMzljNTA0M2MtTHhfQWFHSDE5M2pfR2NjZzZJTW02Rm9kT0xpQXVNQTNQLVVjaVNtYiJ9.b6sEZ8lYbSX_PoqtYa5bV9mPgHFr55uc-vBN6EdfL3KVjsEy2cWtucl7JoCBEb_dRIDZ2PY4ppNfyClYeq1QAQ"
      ansible_connection: httpapi
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_network_os: eos
      ansible_httpapi_port: 443
  children:
    Internet:
      hosts:
        ISP-3:
    SITE1_CE:
      hosts:
        P10:
        Edge14:
    SITE2_CE:
      hosts:
        P20:
        Edge24:
        Edge20:
    MPLS_FABRIC:
      vars:
        ansible_user: arista
        ansible_ssh_pass: arista4qw4 # If using SSH keys, this can be removed
# Use this section if you want to perform testing via the eAPI
        # ansible_connection: httpapi
        # ansible_httpapi_use_ssl: True
        # ansible_httpapi_validate_certs: False
        # ansible_network_os: eos
        # ansible_httpapi_port: 443
# Use this section if you want to perform testing via the CLI through SSH
        ansible_connection: network_cli
        ansible_network_os: eos
        # ansible_become: yes
        # ansible_become_method: enable
      children:
        WAN1:
          children:
            P_ROUTERS:
              vars:
                type: p
              hosts:
                P1:
                  ansible_host: 192.168.0.94
                P2:
                  ansible_host: 192.168.0.96
                P3:
                  ansible_host: 192.168.0.95
                P4:
                  ansible_host: 192.168.0.97
                P5:
                  ansible_host: 192.168.0.91
                P6:
                  ansible_host: 192.168.0.92
            RR_ROUTERS:
              vars: 
                type: rr
              hosts:
                RR5:
                  ansible_host: 192.168.0.73
                RR6:
                  ansible_host: 192.168.0.74
            PE_ROUTERS:
              vars: 
                type: pe
              hosts:
                PE1:
                  ansible_host: 192.168.0.81
                PE2:
                  ansible_host: 192.168.0.82
                PE3:
                  ansible_host: 192.168.0.83
                PE4:
                  ansible_host: 192.168.0.84              
    NETWORK_SERVICES:
      children:
        PE_ROUTERS:

   
