hostname: Leaf22
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Leaf22_lo10
  shutdown: false
  ip_address: 192.168.0.34/32
ethernet_interfaces:
- name: Ethernet1
  peer: H22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.22.254/24
- name: Ethernet2
  peer: Edge20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.22.34.2/24
- name: Ethernet3
  peer: Edge21
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.21.34.2/24
router_bgp:
  as: 65555
  router_id: 192.168.0.34
  neighbors:
    - ip_address: 192.22.34.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.22.34.1
        activate: true
    networks: 
      - prefix: 192.168.0.34/32
    redistribute_routes:
      - source_protocol: connected